var terminals = [
   { name: 'APM1'},
   { name: 'APM2'},
   { name: 'BCW'},
   { name: 'BCTN Alblasserdam'},
   { name: 'Cetem'},
   { name: 'CTN Nijmegen'},
   { name: 'CTT Bad Bentheim'},
   { name: 'CTT Hengelo'},
   { name: 'CTT Rotterdam'},
   { name: 'ECT Delta'},
   { name: 'Euromax'},
   { name: 'Kramer Delta'},
   { name: 'Medrepair'},
   { name: 'MRS'},
   { name: 'PCSA'},
   { name: 'Progeco'},
   { name: 'Progeco 3'},
   { name: 'RSC Waalhaven'},
   { name: 'RST Noord'},
   { name: 'RST Zuid'},
   { name: 'RWG'},
   { name: 'Uniport'},
   { name: 'UWT Botlek'},
   { name: 'UWT Eemhaven'},
   { name: 'UWT Frisohaven'},
   { name: 'UWT Waalhaven'}
];
